name: SmartBudget CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  testiranje:
    runs-on: ubuntu-latest

    steps:
      - name: Preuzimanje koda
        uses: actions/checkout@v4

      - name: Podesavanje Node.js okruzenja
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalacija zavisnosti
        run: npm ci

      - name: Pokretanje automatizovanih testova
        run: npm run test